# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccmcp < Formula
  desc "Dynamic CLI + TUI for managing Claude Code MCP servers, plugins, and per-project overrides"
  homepage "https://github.com/ringo380/ccmcp"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ringo380/ccmcp/releases/download/v0.2.1/ccmcp_0.2.1_darwin_amd64.tar.gz"
      sha256 "a36311abe76a8540675305027f12a9a03fcae9ab80ac152cee0782e09506785b"

      define_method(:install) do
        bin.install "ccmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ringo380/ccmcp/releases/download/v0.2.1/ccmcp_0.2.1_darwin_arm64.tar.gz"
      sha256 "0f44a11d492023d710c3b524a37d6142283939da627fc024b9a837ecddd2eafa"

      define_method(:install) do
        bin.install "ccmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ringo380/ccmcp/releases/download/v0.2.1/ccmcp_0.2.1_linux_amd64.tar.gz"
      sha256 "b8daaf4722672dc80cec969e743219139654638a8d9f4a9039c317e5b07581aa"
      define_method(:install) do
        bin.install "ccmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ringo380/ccmcp/releases/download/v0.2.1/ccmcp_0.2.1_linux_arm64.tar.gz"
      sha256 "a66d1b584518250b49ace0708b5d3089521b240c73d5c778b63f001d9fcc8b74"
      define_method(:install) do
        bin.install "ccmcp"
      end
    end
  end

  test do
    assert_match "ccmcp version", shell_output("#{bin}/ccmcp --version")
  end
end
